"""Offline SQL conversion tests and opt-in, loopback-only PostgreSQL tests."""

from __future__ import annotations

import os
import sqlite3
import uuid
from datetime import datetime, timezone
from urllib.parse import urlparse

import pytest

from backend.storage import (
    Cursor, Row, _safe_error, _script_statements, close_postgres_pools,
    compile_sql, connect_postgres,
)


def test_parameters_are_bound_unchanged_and_never_interpolated():
    untrusted = "'; DROP TABLE users; -- ? % :password"
    plan = compile_sql(
        "SELECT '?' AS q, '100%' AS percentage, ? AS payload -- ? comment\n",
        (untrusted,),
    )
    assert plan.parameters == (untrusted,)
    assert untrusted not in plan.sql
    assert "'?'" in plan.sql
    assert "'100%%'" in plan.sql
    assert plan.sql.count("%s") == 1
    assert untrusted not in repr(plan)


@pytest.mark.parametrize("statement,parameters", [
    ("SELECT ?; SELECT ?", (1, 2)),
    ("SELECT ?1", (1,)),
    ("SELECT ?", ()),
    ("SELECT 1", (1,)),
    ("SELECT 'unclosed", ()),
    ("SELECT 1 /* open", ()),
    ("PRAGMA foreign_keys=OFF", ()),
    ("PRAGMA unsupported=1", ()),
    ("SELECT ?", {"id": 1}),
])
def test_unsafe_or_unsupported_binding_shapes_fail_closed(statement, parameters):
    with pytest.raises(sqlite3.ProgrammingError):
        compile_sql(statement, parameters)


def test_scripts_split_only_outside_literals_comments_and_function_bodies():
    statements = list(_script_statements(
        "SELECT ';?' AS value; -- ; ?\n"
        "SELECT 'quote'';value'; /* nested /* ; */ comment */ "
        "DO $body$ BEGIN PERFORM 1; END $body$;"
    ))
    assert len(statements) == 3
    assert "';?'" in statements[0]
    assert "'quote'';value'" in statements[1]
    assert "PERFORM 1;" in statements[2]


def test_identity_integer_float_foreign_key_and_nocase_ddl():
    plan = compile_sql(
        """CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE COLLATE NOCASE,
            measure REAL, parent_id INTEGER,
            FOREIGN KEY(parent_id) REFERENCES users(id) ON DELETE SET NULL
        )""",
        schema="ff_unit",
    )
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in plan.sql
    assert "DOUBLE PRECISION" in plan.sql
    assert "DEFERRABLE INITIALLY IMMEDIATE" in plan.sql
    assert "AUTOINCREMENT" not in plan.sql
    assert "NOCASE" not in plan.sql
    assert plan.identity_table == "users"
    assert len(plan.followup_sql) == 1
    assert '"ff_unit"."users"' in plan.followup_sql[0]
    assert "translate" in plan.followup_sql[0]
    assert "abcdefghijklmnopqrstuvwxyz" in plan.followup_sql[0]


def test_native_postgres_identity_and_deferrable_are_not_duplicated():
    plan = compile_sql(
        """CREATE TABLE parent (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          parent_id BIGINT REFERENCES parent(id) DEFERRABLE INITIALLY IMMEDIATE)"""
    )
    assert plan.sql.count("IDENTITY") == 1
    assert plan.sql.count("DEFERRABLE") == 1


def test_insert_ignore_and_explicit_returning_do_not_conflict():
    ignored = compile_sql("INSERT OR IGNORE INTO radar_events (event_key) VALUES (?)", ("a",))
    assert "ON CONFLICT DO NOTHING RETURNING id" in ignored.sql
    assert ignored.implicit_returning
    explicit = compile_sql(
        "INSERT INTO radar_locks(lock_name,owner) VALUES (?,?) "
        "ON CONFLICT(lock_name) DO UPDATE SET owner=excluded.owner RETURNING owner",
        ("test", "owner"),
    )
    assert explicit.sql.endswith("RETURNING owner")
    assert not explicit.implicit_returning


@pytest.mark.parametrize("statement", [
    "SELECT * FROM users WHERE username = ? COLLATE NOCASE",
    "SELECT * FROM users WHERE username COLLATE NOCASE = ?",
])
def test_nocase_comparison_folds_both_operands(statement):
    plan = compile_sql(statement, ("TeSt",))
    assert plan.sql.count("translate") == 2
    assert "NOCASE" not in plan.sql
    assert plan.parameters == ("TeSt",)


def test_like_uses_sqlite_ascii_case_and_preserves_literal_percent():
    plan = compile_sql("SELECT * FROM jobs WHERE source=? OR tags LIKE '%AI网页搜索%'", ("source",))
    assert plan.sql.count("translate") == 2
    assert "'%%AI网页搜索%%'" in plan.sql
    assert "ILIKE" not in plan.sql


def test_date_json_and_julianday_conversion():
    plan = compile_sql(
        "SELECT DATE('now'), datetime('now'), julianday(?), "
        "json_extract(?, '$.verification_status')", ("2026-08-30", '{"verification_status":"pending"}'),
        schema="ff_unit",
    )
    assert plan.sql.count("AT TIME ZONE 'UTC'") == 2
    assert '"ff_unit" . _ff_julianday' in plan.sql
    assert "#>> ARRAY" in plan.sql
    assert plan.parameters[0] == "2026-08-30"


def test_pragma_uses_only_parameterised_table_and_explicit_private_schema():
    plan = compile_sql("PRAGMA table_info(users)", schema="ff_unit")
    assert plan.parameters == ("ff_unit", "users")
    assert "information_schema.columns" in plan.sql
    with pytest.raises(sqlite3.ProgrammingError):
        compile_sql("PRAGMA table_info('users;DROP TABLE users')")


def test_rows_support_dictionary_indexing_and_value_unpacking():
    row = Row(("id", "label"), (7, "test"))
    assert row["id"] == row["ID"] == row[0] == 7
    assert tuple(row) == (7, "test")
    assert dict(row) == {"id": 7, "label": "test"}
    assert row[:] == (7, "test")
    cursor = Cursor([row, row], names=row.keys(), rowcount=2)
    assert cursor.fetchone() is row
    assert cursor.fetchmany(2) == [row]
    assert cursor.fetchall() == []
    assert cursor.description[0][0] == "id"


def test_provider_error_contains_no_message_or_secret():
    class SensitiveError(Exception):
        sqlstate = "23505"

    error = _safe_error(SensitiveError("password=secret-dsn PRIVATE user payload"))
    assert isinstance(error, sqlite3.IntegrityError)
    assert "23505" in str(error)
    assert "secret" not in str(error)
    assert "PRIVATE" not in str(error)


@pytest.mark.parametrize("dsn,schema,timeout,max_size", [
    ("", "frostfire", 1, 1),
    ("unavailable", "public;DROP SCHEMA public", 1, 1),
    ("unavailable", "frostfire", 0, 1),
    ("unavailable", "frostfire", float("nan"), 1),
    ("unavailable", "frostfire", 1, 100),
])
def test_configuration_validation_does_not_connect(dsn, schema, timeout, max_size):
    with pytest.raises(sqlite3.Error):
        connect_postgres(dsn, schema=schema, timeout=timeout, max_size=max_size)


@pytest.mark.parametrize("schema", [
    "public", "auth", "storage", "realtime", "extensions", "information_schema",
    "graphql", "graphql_public", "supabase_functions", "supabase_migrations", "PG_catalog",
])
def test_managed_schemas_are_rejected_before_connecting(schema):
    with pytest.raises(sqlite3.ProgrammingError, match="private application schema"):
        connect_postgres("postgresql://unused.invalid/test", schema=schema)


@pytest.mark.parametrize("mode", ["disable", "prefer", "require", "verify-ca", "verify-full"])
def test_remote_connections_never_downgrade_tls_verification(monkeypatch, mode):
    psycopg = pytest.importorskip("psycopg")
    observed = []

    def no_connection(*args, **kwargs):
        observed.append(kwargs)
        raise RuntimeError("DO_NOT_LOG_PROVIDER_CONNECTION_DETAILS")

    monkeypatch.setattr(psycopg, "connect", no_connection)
    try:
        with pytest.raises(sqlite3.OperationalError) as caught:
            connect_postgres(f"postgresql://unused.invalid/test?sslmode={mode}", timeout=0.1)
        assert observed[0]["sslmode"] == "verify-full"
        assert "DO_NOT_LOG" not in str(caught.value)
    finally:
        close_postgres_pools()


@pytest.mark.parametrize("host", [
    "aws-0-ap-southeast-1.pooler.supabase.com",
    "AWS-0-AP-SOUTHEAST-1.POOLER.SUPABASE.COM",
    "aws-0-ap-southeast-1.pooler.supabase.com.",
])
def test_supabase_transaction_pooler_rejected_before_connect(monkeypatch, host):
    psycopg = pytest.importorskip("psycopg")
    attempts = []

    def unexpected_connection(*args, **kwargs):
        attempts.append(True)
        raise AssertionError("Transaction pooler must not be contacted")

    monkeypatch.setattr(psycopg, "connect", unexpected_connection)
    try:
        with pytest.raises(sqlite3.OperationalError):
            connect_postgres(f"postgresql://{host}:6543/postgres", timeout=0.1)
        assert not attempts
    finally:
        close_postgres_pools()


@pytest.fixture
def pg():
    dsn = os.environ.get("FROSTFIRE_TEST_POSTGRES_URL", "")
    if not dsn:
        pytest.skip("FROSTFIRE_TEST_POSTGRES_URL is not set.")
    parsed = urlparse(dsn)
    if parsed.hostname not in {"localhost", "127.0.0.1", "::1"}:
        pytest.fail("Storage integration tests require an isolated loopback PostgreSQL.")
    psycopg = pytest.importorskip("psycopg")
    schema = "ff_storage_test_" + uuid.uuid4().hex

    def connect(**kwargs):
        return connect_postgres(dsn, schema=schema, **kwargs)

    yield connect, dsn, schema
    close_postgres_pools()
    # The identifier is generated here, never obtained from application data.
    with psycopg.connect(dsn, autocommit=True) as connection:
        connection.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')


def test_pg_connect_does_not_create_schema_and_rollback_removes_new_schema(pg):
    connect, dsn, schema = pg
    import psycopg
    connection = connect()
    with psycopg.connect(dsn) as observer:
        assert observer.execute("SELECT 1 FROM pg_namespace WHERE nspname=%s", (schema,)).fetchone() is None
    connection.ensure_schema()
    connection.execute("CREATE TABLE entries (id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT)")
    connection.rollback()
    connection.close()
    with psycopg.connect(dsn) as observer:
        assert observer.execute("SELECT 1 FROM pg_namespace WHERE nspname=%s", (schema,)).fetchone() is None
    with connect() as connection:
        connection.execute("CREATE TABLE entries (id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT)")
        assert connection.execute("INSERT INTO entries(content) VALUES (?)", ("saved",)).lastrowid == 1


def test_pg_identity_commit_duplicate_recovery_and_ascii_username(pg):
    connect, _, _ = pg
    with connect() as connection:
        connection.executescript(
            "CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE COLLATE NOCASE);"
        )
        first = connection.execute("INSERT INTO users(username) VALUES (?)", ("CaseName",))
        assert isinstance(first.lastrowid, int)
        with pytest.raises(sqlite3.IntegrityError):
            connection.execute("INSERT INTO users(username) VALUES (?)", ("CASENAME",))
        assert connection.execute("SELECT COUNT(*) FROM users").fetchone()[0] == 1
        connection.execute("INSERT INTO users(username) VALUES (?)", ("Ä",))
        connection.execute("INSERT INTO users(username) VALUES (?)", ("ä",))
    with connect() as connection:
        row = connection.execute("SELECT * FROM users WHERE username = ? COLLATE NOCASE", ("casename",)).fetchone()
        assert row["id"] == first.lastrowid
        assert row["username"] == "CaseName"
        assert connection.execute("SELECT COUNT(*) FROM users").fetchone()[0] == 3


def test_pg_literals_null_dates_unicode_and_sql_injection_are_values(pg):
    connect, _, _ = pg
    with connect() as connection:
        connection.ensure_schema()
        row = connection.execute("SELECT '?' AS question, '100%' AS percent, ? AS value", ("'; DROP SCHEMA x; % ?",)).fetchone()
        assert tuple(row) == ("?", "100%", "'; DROP SCHEMA x; % ?")
        row = connection.execute(
            "SELECT DATE('now') AS day, datetime('now') AS instant, "
            "julianday(?) AS first, julianday(?) AS same, julianday(?) AS invalid, "
            "json_extract(?, '$.verification_status') AS status",
            ("2026-08-30T01:00:00+01:00", "2026-08-30T00:00:00Z", "invalid-date",
             '{"verification_status":"pending"}'),
        ).fetchone()
        assert row["day"] == datetime.now(timezone.utc).date().isoformat()
        assert row["first"] == row["same"]
        assert row["invalid"] is None
        assert row["status"] == "pending"
        assert connection.execute("SELECT ? LIKE ?", ("AbC招聘", "%aBc%")).fetchone()[0] is True
        assert connection.execute("SELECT ? LIKE ?", ("Ä", "ä")).fetchone()[0] is False
        with sqlite3.connect(":memory:") as reference:
            for value, pattern in ((r"a\b", r"a\b"), (r"a\_b", r"a\_b"), ("a_b", r"a\_b")):
                expected = reference.execute("SELECT ? LIKE ?", (value, pattern)).fetchone()[0]
                actual = connection.execute("SELECT ? LIKE ?", (value, pattern)).fetchone()[0]
                assert actual == bool(expected)


def test_pg_pragma_identity_deferrable_and_large_numeric_roundtrip(pg):
    connect, dsn, schema = pg
    with connect() as connection:
        connection.executescript("""
            CREATE TABLE parent(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
            CREATE TABLE child(id INTEGER PRIMARY KEY, parent_id INTEGER, score REAL,
                FOREIGN KEY(parent_id) REFERENCES parent(id) ON DELETE CASCADE);
        """)
        columns = {row["name"]: dict(row) for row in connection.execute("PRAGMA table_info(child)").fetchall()}
        assert columns["id"]["pk"] == 1
        assert columns["parent_id"]["type"] == "bigint"
        assert columns["score"]["type"] == "double precision"
        connection.execute("SET CONSTRAINTS ALL DEFERRED")
        connection.execute("INSERT INTO child VALUES (?, ?, ?)", (2**50, 2**40, 0.1234567890123456))
        connection.execute("INSERT INTO parent(id,name) VALUES (?, ?)", (2**40, "parent"))
    with connect() as connection:
        row = connection.execute("SELECT id,score FROM child").fetchone()
        assert row[0] == 2**50
        assert row[1] == 0.1234567890123456
        connection.execute("DELETE FROM parent WHERE id=?", (2**40,))
        assert connection.execute("SELECT COUNT(*) FROM child").fetchone()[0] == 0
    import psycopg
    with psycopg.connect(dsn) as connection:
        row = connection.execute(
            "SELECT condeferrable, condeferred FROM pg_constraint c "
            "JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname=%s AND contype='f'",
            (schema,),
        ).fetchone()
        assert row == (True, False)


def test_pg_executemany_rowcount_explicit_returning_and_ignore(pg):
    connect, _, _ = pg
    with connect() as connection:
        connection.execute("CREATE TABLE radar_events(id INTEGER PRIMARY KEY AUTOINCREMENT, event_key TEXT UNIQUE)")
        cursor = connection.executemany("INSERT INTO radar_events(event_key) VALUES (?)", [("a",), ("b",)])
        assert cursor.rowcount == 2
        assert cursor.lastrowid is None
        ignored = connection.execute("INSERT OR IGNORE INTO radar_events(event_key) VALUES (?)", ("a",))
        assert ignored.rowcount == 0
        assert ignored.lastrowid is None
        explicit = connection.execute(
            "INSERT INTO radar_events(event_key) VALUES (?) RETURNING id,event_key", ("c",)
        )
        assert explicit.fetchone()["event_key"] == "c"
        changed = connection.execute("UPDATE radar_events SET event_key=? WHERE event_key=?", ("d", "b"))
        assert changed.rowcount == 1


def test_pg_pool_is_bounded_and_context_returns_connection(pg):
    connect, _, _ = pg
    first = connect(max_size=1)
    try:
        with pytest.raises(sqlite3.OperationalError, match="busy"):
            connect(max_size=1, timeout=0.03)
    finally:
        first.close()
    with connect(max_size=1, timeout=1) as connection:
        assert connection.execute("SELECT 1").fetchone()[0] == 1
    with pytest.raises(sqlite3.ProgrammingError, match="closed"):
        connection.execute("SELECT 1")


def test_pg_private_schema_and_new_objects_have_no_public_privileges(pg):
    connect, dsn, schema = pg
    with connect() as connection:
        connection.execute("CREATE TABLE private_rows(id INTEGER PRIMARY KEY AUTOINCREMENT, value TEXT)")
    import psycopg
    with psycopg.connect(dsn) as connection:
        public_schema_grants = connection.execute(
            "SELECT COUNT(*) FROM pg_namespace n, "
            "LATERAL aclexplode(COALESCE(n.nspacl,acldefault('n',n.nspowner))) a "
            "WHERE n.nspname=%s AND a.grantee=0", (schema,),
        ).fetchone()[0]
        assert public_schema_grants == 0
        public_table_grants = connection.execute(
            "SELECT COUNT(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace, "
            "LATERAL aclexplode(COALESCE(c.relacl,acldefault('r',c.relowner))) a "
            "WHERE n.nspname=%s AND c.relkind='r' AND a.grantee=0", (schema,),
        ).fetchone()[0]
        assert public_table_grants == 0
